name: Kiza

on:
  push:
    branches:
      - main

jobs:
  myDeployment:
    runs-on: ubuntu-latest
    steps:
      - name: For pick the repository
        uses: actions/checkout@v4
      - name: for connection
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{secrets.IP}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}

          script: |
            cd /home/rajni/frontendkiza/
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 24
            git pull origin main
            npm i
            npm run build
            cd dist/front-end/
            sudo npm i pm2 -g
            pm2 start --name "Kiza Frontend" /home/rajni/.nvm/versions/node/v24.18.0/bin/http-server -- -p 4200 -d false
